const SUBSCRIBE_GET_MESSAGES_TO_FIREBASE = 'SUBSCRIBE_GET_MESSAGES_TO_FIREBASE';
const UNSUBSCRIBE_GET_MESSAGES_FROM_FIREBASE = 'UNSUBSCRIBE_GET_MESSAGES_FROM_FIREBASE';
const UPDATE_MESSAGES = 'UPDATE_MESSAGES';

const POST_MESSAGE = 'POST_MESSAGE';
const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

export {
  SUBSCRIBE_GET_MESSAGES_TO_FIREBASE,
  UNSUBSCRIBE_GET_MESSAGES_FROM_FIREBASE,
  UPDATE_MESSAGES,
  POST_MESSAGE,
  POST_MESSAGE_SUCCESS,
  POST_MESSAGE_ERROR
};
